services:
  server:
    build: "./server"
    ports:
      - "8080:8080"
    env_file:
      - "./server/.env"
    restart:
      unless-stopped
  client:
    build: "./client"
    ports:
      - "3000:3000"
    env_file:
      - "./client/.env"
    restart: unless-stopped