services:
  app:
    # image: social_network-app:latest
    build: .
    ports:
      - "443:5000"
    env_file:
      - .env.production
    # volumes:
    #   - /root/uploads:/app/uploads
    restart:
      unless-stopped
